# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  twig.extension.text:
     class: Twig_Extensions_Extension_Text
     tags:
         - { name: twig.extension }
  xlf_loader:
    class: JMS\TranslationBundle\Translation\Loader\XliffLoader
    tags:
        - { name: xlf.loader }

  colme.form.type.collectible:
    class: CollecMe\CollectionBundle\Form\Type\CollectibleType
    tags:
        - { name: colmeColType, alias: colmeColType }
        
jms_translation:
    source_language: en
    locales: [fr,en,de]

    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src,%kernel.root_dir%/Resources/translations]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            extractors: [jms_i18n_routing]

jms_i18n_routing:
    default_locale: fr
    locales: [fr, en, de]
    strategy: prefix_except_default
